#!/bin/bash
#
# shadowmanager main program, the computer science internal assigment.
#
# usage: shadowmanager <command> [arguments ...]
# use './shadowmanager usage' for more informations.

cd "$(dirname "$0")"

. ./conf/shadowmanager.conf
. ./lang/$LANGUAGE.lng

function debug {
        [[ ! -z $DEBUG ]] && echo "[$(echo ${FUNCNAME[*]}|tr ' ' '/')] $*"
}

function _shadowmanager_load {
        [[ -z $(cat $1 | grep "shadowmanager-ignore") ]] && . ./$1 && debug "load: loaded $1" || debug "load: ignored $1"
}

for inc in $(ls ./include/)
do
        _shadowmanager_load ./include/$inc
done

for ovr in $(ls ./override/)
do
        _shadowmanager_load ./override/$ovr
done

ifroot
[[ -z $* ]] && usage || shadowmanager_exec $*
