#!/bin/bash
UPDATE_URL='https://github.com/NATSOFT/shadowmanager/archive/master.zip'

echo "Updating shadowmanager... "
wget $UPDATE_URL 2> /dev/null > /dev/null 
tar zxf master.zip 
rm master.zip
echo "Update complete."
