#!/bin/bash
cd "$(dirname "$0")"
[[ -e .update ]] && rm -fr .update
mkdir .update
cd .update 
UPDATE_URL='https://github.com/NATSOFT/shadowmanager/archive/master.zip'

echo "Updating shadowmanager... "
wget $UPDATE_URL 2> /dev/null > /dev/null 
unzip master.zip 
rm master.zip
cd shadowmanager-*/
cp ../../conf/shadowmanager.conf{,.old}
cp -R . ../../
cd ../../
update_ovr="$(ls ./override/)"
for _ovr_update in $update_ovr
do
	cp ./override-available/$_ovr_update ./override/
done
echo "Update complete. Your shadowmanager.conf was moved to shadowmanager.conf.old."
rm -fr ../../.update
