#!/bin/bash
# add: add a server
# usage: add <port> <pass> <method>

function add {
	[[ -z "$3" ]] && echo "add: $MISSING_ARGS" && return 1
	[[ $(verify "$@") == "false" ]] && echo "$CONTAIN_INVALID_CHARS" && return 1
	[[ -e "$SHADOW_CONF" && ! -z $(grep "{$1," < "$SHADOW_CONF" | awk -F"{" '{print $2}' | awk -F"," '{print $1}') ]] && echo "$PORT_ALREADY_IN_USE" && return 1
	(! grep -q " $3 " <<< "$METHODS" ) && sed -e "s/__METHOD__/$3/" <<< "$ERR_METHOD_NOT_EXIST" && return 1
	hook pre-add
	echo "($3){$1,$2}" >> "$SHADOW_CONF"
	echo "$SERVER_ADDED"
	hook post-add
}
