#!/bin/bash
# start: start shadowservers
function start {
	[[ -e $PIDS ]] && echo start: $ERR_RUNNING && return 1
	genconf
	[[ ! -e $LOGDIR ]] && mkdir $LOGDIR
	echo -n "$STARTING_SERVERS"
	cd $SHADOW_JSON_DIR
	hook pre-start
	for server in $(ls)
	do
		_log=$server-$(date +%Y-%m-%d_%H:%M:%S)
		$(echo $SHADOW_CMD|sed -e "s/__CONFIG__/$server/") 2>> ../../$LOGDIR/$_log >> ../../$LOGDIR/$_log
		[[ -z $(cat $SS_PID) ]] && echo $ERR_CAN_NOT_START && stop && crash 1
		echo $(cat $SS_PID) >> $PIDS
		rm $SS_PID
	done
	echo $DONE
	hook post-start
}

function stop {
	[[ ! -e $PIDS ]] && echo stop: $ERR_NOT_RUNNING && return 1
	hook pre-stop
	echo -n "$STOPPING_SERVERS"
	for kill in $(cat $PIDS)
	do
		kill $kill > /dev/null 2> /dev/null
	done
	rm -f $PIDS
	echo $DONE
	hook post-stop
}

function restart {
	stop; start
}

