#!/bin/bash
# start: start shadowservers
function start {
	[[ -e "$PIDS" ]] && echo "start: $ERR_RUNNING" && return 1
	[[ ! $1 == "--no-genconf" ]] && genconf
	[[ ! -e "$LOGDIR" ]] && mkdir "$LOGDIR"
	echo -n "$STARTING_SERVERS"
	cd "$SHADOW_JSON_DIR" || exit 1
	hook pre-start
	for server in *
	do
		debug "starting $server"
		_log=$server-$(date +%Y-%m-%d_%H:%M:%S)
		eval "$(sed -e "s/__CONFIG__/$server/" <<< "$SHADOW_CMD")" 2>> "../../$LOGDIR/$_log" >> "../../$LOGDIR/$_log"
		debug "output: $(cat "../../$LOGDIR/$_log")"
		[[ -z $(cat "$SS_PID") ]] && echo "$ERR_CAN_NOT_START" && stop && crash 1
		cat "$SS_PID" >> "$PIDS"
		rm "$SS_PID"
	done
	echo "$DONE"
	hook post-start
}

function stop {
	[[ ! -e $PIDS ]] && echo "stop: $ERR_NOT_RUNNING" && return 1
	hook pre-stop
	echo -n "$STOPPING_SERVERS"
	while IFS= read -r kill < "$PIDS"
	do
		debug "kill $kill"
		kill "$kill" > /dev/null 2> /dev/null
	done
	rm -f "$PIDS"
	echo "$DONE"
	hook post-stop
}

function restart {
	genconf; stop; start --no-genconf
}


