#!/bin/bash

function crash {
	stop; exit "$1"
}

function usage {
	echo '
shadowmanager is a script to maintaince multiple shadowsocks server with
different encryption method at a time.

shadowsocks-python is tested and it works.

usage: shadowmanager add <port> <password> <method>
                     start
                     stop
                     restart
                     status
                     show
                     remove <id>
                     enovr [overrides ...]
                     disovr [overrides ...]
	             edit <server_id> <pass|port|method> <new_value>

commands explained:

	add:     add a server to shadowmanager handler, accepting 3 parameters,
	         port, password and method.
	start:   start shadowmanager, no parameters required.
	stop:    stop shadowmanager, no parameters required.
	restart: restart shadowmanager, no parameters required.
	show:    show all the servers handling, no parameters required.
	status:  show shadowmanager running status, no parameters required.
	remove:  remove server with given ID. Use "show" command to show all
	         servers, accepting 1 parameter, server ID.
	enovr:   enable one or more overrides, accepting override names as
	         parameters (optional).
	disovr:  disable one or more overrides, accepting override names as
	         parameters (optional).
	edit:    edit a shadowsocks server, accepting 3 paramaters, server ID, 
	         operation, and new value.
'
	_show-extra-helps
}
