#!/bin/bash

function ifroot {
	[[ $CHECK_ROOT == "true" && "$(id -u)" != "0" ]] && {
		echo "$ROOT_REQUIRED"
		exit 1
	}
}

function shadowmanager_exec {
	if [[ ! -z "$@" ]]
	then
		if ! type "$1" > /dev/null 2> /dev/null
		then
			debug "call $1"
			echo "shadowmanager: command not found: $1"
			return 127
		else
			eval "$@"
		fi
	fi
}

# verify: verify if the input is valid
# usage: verify <string>

function verify {
	for char in $INVALID_CHARS
	do
		debug "check if exist $char"
		if [[ "$@" == *"$char"* ]]
		then
			echo false; return
		fi
	done
}
