#!/bin/bash
# show: show handling servers
# usage: show

function show {
	id=0
	[[ ! -z $1 ]] && _servers=$SHADOW_CONF.tmp || _servers=$SHADOW_CONF
	echo "ID	(method){port,password}"
	for _server in $(cat $_servers)
	do
		let id++
		echo "$id	$_server"
	done
}
