#!/bin/bash
#
# Shadowmanager system variables
#

SHADOWSOCKS_JSON_PRE="
{
    \"server\": \"$SERVER_ADDR\",
    \"port_password\": {"
SHADOWSOCKS_JSON_EXT="
    },
    \"timeout\": $TIMEOUT,
    \"method\": \"__METHOD__\",
    \"fast_open\": __FAST_OPEN__
}"
INVALID_CHARS="[ ] { } \  , ( ) __METHOD__ __FAST_OPEN__"
