#!/bin/bash
# This override encrypt the server password using base64.
# This will enable user to use char such as { } , [ ] ( ) in password.

function genconf {
	rm -f $SHADOW_JSON_DIR/* 2> /dev/null
	[[ ! -e $SHADOW_JSON_DIR ]] && mkdir $SHADOW_JSON_DIR
	echo -n "$GEN_SS_CONF"
	for method in $METHODS
	do
		{
			[[ ! -z $(cat $SHADOW_CONF|grep \($method\)) ]] && {
				servers=$(cat $SHADOW_CONF|grep \($method\)|sed '$ d')
				_last=$(cat $SHADOW_CONF|grep \($method\)|tail -n1)
				echo $SHADOWSOCKS_JSON_PRE > $SHADOW_JSON_DIR$method.conf.tmp
				for server in $servers
				do
					_port=$(echo $server|awk -F "[{},]" '{print $2}')
					_pass=$(echo $server|awk -F "[{},]" '{print $3}'|base64 -D)
					echo "\"$_port\": \"$_pass\"," >> $SHADOW_JSON_DIR$method.conf.tmp
				done
				_port=$(echo $_last|awk -F "[{},]" '{print $2}')
				_pass=$(echo $_last|awk -F "[{},]" '{print $3}'|base64 -D)
				echo "\"$_port\": \"$_pass\"" >> $SHADOW_JSON_DIR$method.conf.tmp
				echo $SHADOWSOCKS_JSON_EXT >> $SHADOW_JSON_DIR$method.conf.tmp
				cat $SHADOW_JSON_DIR$method.conf.tmp|sed -e "s/__FAST_OPEN__/$TCP_FAST_OPEN/; s/__METHOD__/$method/;" > $SHADOW_JSON_DIR$method.conf
				rm $SHADOW_JSON_DIR$method.conf.tmp
			}
		} &
	done
	wait
	echo $DONE
}

function add {
  _pass=$(echo $2 | base64)
	[[ -z $3 ]] && echo "add: $MISSING_ARGS" && return 1
	[[ $(verify $1 $3) == "false" ]] && echo "$CONTAIN_INVALID_CHARS" && return 1
	[[ -e $SHADOW_CONF && ! -z $(cat $SHADOW_CONF | grep {$1, | awk -F{ '{print $2}' | awk -F, '{print $1}') ]] && echo "$PORT_ALREADY_IN_USE" && return 1
	[[ -z $(echo $METHODS | grep \ $3\ ) ]] && echo $(echo "$ERR_METHOD_NOT_EXIST"|sed -e "s/__METHOD__/$3/") && return 1
	echo "($3){$1,$_pass}" >> $SHADOW_CONF
	echo $SERVER_ADDED
}

function show {
	id=0
	[[ ! -z $1 ]] && _servers=$SHADOW_CONF.tmp || _servers=$SHADOW_CONF
	echo "ID	(method){port,password}"
	for _server in $(cat $_servers)
	do
		let id++
    _method=$(echo $_server|awk -F "[()]" '{print $2}')
    _port=$(echo $_server|awk -F "[{},]" '{print $2}')
    _pass=$(echo $_server|awk -F "[{},]" '{print $3}'|base64 -D)
		echo "$id	($_method){$_port,$_pass}"
	done
}
