#!/bin/bash
# This override eanble shadowmanager to convert .json shadowsocks configure file to shadowmanager configure file.
# usage: ./shadowmanager json2manager <json_file> <output_file>

echo "	json2manager: convert .json shadowsocks configure file to shadowmanager configure file." | add-help
echo "	json2manager <encrypt_method> <json_file> <output_file>" | add-usage
echo "	json2manager: 将 .json 格式的 shadowsocks 配置文件转换成 shadowmanager 的配置文件。" | add-help chinese
echo "	json2manager <加密方式> <json 文件> <输出文件>" | add-usage chinese

debug "added json2manager, by json to shadowmanager"
add-ui Convert_json_shadowsocks_cfg_file_to_shadowmanager_cfg_file ui_json2man

function ui_json2man {
	local _j2m_TEMP=$(mktemp)
	let i=1;
	local _enc=""
	for _method in $METHODS
	do
		echo $_method >> $_j2m_TEMP
		local _enc="$_enc $i $_method"
		let i++
	done

	dialog \
			--keep-window --begin 2 2 --menu "Encryption:" 0 40 0 $_enc \
	--and-widget	--keep-window --begin 4 4 --inputbox "Path to json file: " 0 0 \
	--and-widget    --keep-window --begin 6 6 --inputbox "Output dir:" 0 0 \
	2> $_j2m_TEMP.selection

	[[ ! $? == 0 ]] && rm $_j2m_TEMP* && return 1

	local method_id=$(cat $_j2m_TEMP.selection | awk -F'\t' '{print $1}')
	local method=$(cat $_j2m_TEMP | sed -n "${method_id}p")
	local json=$(cat $_j2m_TEMP.selection | awk -F'\t' '{print $2}')
	local output=$(cat $_j2m_TEMP.selection | awk -F'\t' '{print $3}')

	json2manager $method $json $output

	dialog --msgbox "Done."

	rm $_j2m_TEMP*
	return 0
}

function json2manager {
	[[ -z $3 ]] && echo "usage: ./shadowmanager json2manager <encrypt_method> <json_file> <output_file>" && return 1
	_method=$1
	_accts=$(cat $2 | tr -d '\n' | awk -F'"port_password": {|}' '{print $2}'| tr -d '" ' | tr "," " ")
	mv $SHADOW_CONF $SHADOW_CONF.$$.bak
	for _acct in $_accts
	do
		_port=$(echo $_acct|awk -F: '{print $1}')
		_pass=$(echo $_acct|awk -F: '{print $2}')
		add $_port $_pass $_method > /dev/null # Using add instead of creating configure, because base64.
	done
	mv $SHADOW_CONF $3
	mv $SHADOW_CONF.$$.bak $SHADOW_CONF
}
