#!/bin/bash
# This override allow users to generate random passwords for their shadowsocks servers.
# usage: add-randpass <port> <method> [password-lenght]

DEFAULT_PASSWD_LEN=32

echo "	add-randpass: add a server with a random password." | add-help
echo "	add-randpass <port> <method> [password_len]" | add-usage
echo "	add-randpass: 添加一个随机密码的服务器。" | add-help chinese
echo "	add-randpass <端口> <加密方法> [密码长度]" | add-usage chinese

debug "added internal function _getrandpass, by randpass"

function _getrandpass {
	# We are using LC_CTYPE=C here to makes OSX etc works porperly.
	[[ -z $1 ]] && LC_CTYPE=C tr -dc 'A-Za-z0-9_' < /dev/urandom | head -c $DEFAULT_PASSWD_LEN || LC_CTYPE=C tr -dc 'A-Za-z0-9_' < /dev/urandom | head -c $1
}

debug "added add-randpass, by randpass"

function add-randpass {
	[[ -z $2 ]] && echo -e "usage: add-randpass <port> <method> [password-lenght]\nThe default password lenght is $DEFAULT_PASSWD_LEN." && return 1
	_pass=$(_getrandpass $3)
	echo "Password generated: $_pass"
	add $1 $_pass $2
}
