#!/bin/bash
# This override provide a timer, and limit the time of each shadowsocks server can use in hours. This override will hooks pre-add events so make sure you are not using some override that remove pre-add events. Cronjob will be added to check the status and remove expired accounts.
# Two hookers are provided in this override. timelim-add, which call when pre-add. timelim-corn, which call when cronjob execute.

INVALID_CHARS="$INVALID_CHARS |"

function init-timelim {
	[[ -e .cron.tmp ]] && return 0
	echo "Installing timelim..."
	touch .timelim
	crontab -l >> .cron.tmp
	echo "00 * * * * $0 timelim-update"
	[[ -e $SHADOW_CONF ]] && echo "SHADOW_CONF already exist... Might cause problems."
}

function pre-add {
	hook timelim-add
	_time=$(date +%s)
	read -p "Account duration(hrs)? " dur
	let _dur=$_dur*3600
	let _due=$_time+$_dur
	echo -n "$_due|" >> $SHADOW_CONF
}

function timelim-update {
	hook timelim-corn
	id=0
	_now=$(date +%s)
	_restart=no
	for _server in $(cat $_servers)
	do
		let $id++
		_this_due=$(echo $_server | awk -F"|" '{print $1}')
		[[ $_this_due -gt $_now ]] && {
			echo "$_server has expired. Moved to $SHADOW_CONF.disabled"
			_restart=yes
			echo $_server >> $SHADOW_CONF.disabled
			sed -e "${id}d" $SHADOW_CONF > $SHADOW_CONF.tmp
			mv $SHADOW_CONF.tmp $SHADOW_CONF
		}
	done
	[[ $_restart == "yes" ]] && restart
}

init-timelim
