#!/bin/bash
# This override make shadowmanager start the server use screen instead of daemon.

SHADOW_CMD=$(echo $SHADOW_CMD | sed -e 's/-d start//g;')
ERR_IN_SCREEN_MODEenglish="You are currently in screen mode, you will have to stop/restart server(s) manualy."
ERR_IN_SCREEN_MODEchinese="你现在在使用 screen 模式，你需要手动停止／重启服务器。"

function start {
  genconf
  echo -n "$STARTING_SERVERS"
  cd $SHADOW_JSON_DIR
  for server in $(ls)
  do
    screen -dmS shadowsocks-$server $(echo $SHADOW_CMD|sed -e "s/__CONFIG__/$server/")
  done
  echo $DONE
}

function stop {
	eval echo \$ERR_IN_SCREEN_MODE$LANGUAGE
	return 1
}

function restart {
	stop
}
