#!/bin/bash
# This override enable shadowmanager to show usage in Chinese

[[ ! $LANGUAGE == "chinese" ]] && return 0

debug "overrided usage, by chinese-usage"

function usage {
echo '
shadowmanager 是一个用于同时维护多个不同加密的 shadowsocks 服务器的脚本。

此脚本在 shadowsocks-python 下测试通过。

用法：shadowmanager add <端口> <密码> <加密>
                    start
                    stop
                    restart
                    status
                    show
                    remove <id>

参数解释：

	add:     添加一个服务器到 shadowmanager 的管理，需要 3 个参数。端口，
	         密码，和方法。
	start:   启动 shadowmanager，无需参数。
	stop:    停止 shadowmanager，无需参数。
	restart: 重启 shadowmamager，无需参数。
	status:  检视 shadowmanager 状态，无需参数。
	show:    显示所有 shadowsocks 服务器，无需参数。
	remove:  移除指定 ID 的 shadowsocks 服务器，使用 "show" 来查看所有服务
	         器，需要 1 个参数，服务器 ID。
'
  _show-extra-helps
}
