#!/bin/bash
# This override will start each server in both IPv6 and IPv4.

SERVER_ADDR=0.0.0.0

debug hooked post-start by ipv6 override

function post-start {
	cd ../..
	mv $PIDS{,.ipv4}
	SERVER_ADDR="::"
	SHADOWSOCKS_JSON_PRE="
{
    \"server\": \"$SERVER_ADDR\",
    \"port_password\": {"
	[[ $SERVER_ADDR == "::" ]] && return 0
	start
	cat $PIDS.ipv4 >> $PIDS
	rm $PIDS.ipv4
}
