#!/bin/bash

echo "	gui: open shadowmanager GUI" | add-help
echo "  gui: 开启 shadowmanager GUI" | add-help chinese

function gui {
	while true
	do
		_gui
	done
}

function cfm_restart {
	dialog --yesno "Restart shadowmanager?" 0 0
	[[ $? == 0 ]] && {
		restart 
		read -p "Press [ENTER] key to continue..."
	}
}

function _gui {

	local TEMP=$(mktemp)

	dialog --menu "shadowmanager-gui" 0 50 0 \
		a "(A)dd a server" \
		c "server (C)ontrol" \
		o "(O)verride manager" \
		r "(R)emove a server" \
		s "(S)how servers" \
		e "(E)xecute shadowmanager command" \
		p "(P)lugins menu" \
		q "(Q)uit shadowmanager" 2> $TEMP
	[[ ! $? == 0 ]] && echo q > $TEMP

	case $(cat $TEMP) in
		a) {
			local _serveradd_TEMP=$(mktemp)
			let i=1;
			local _enc=""
			for _method in $METHODS
			do
				echo $_method >> $_serveradd_TEMP
				local _enc="$_enc $i $_method"
				let i++
			done

			dialog \
					--keep-window --begin 2 2 --inputbox "Port to listen on: " 0 0 \
			--and-widget	--keep-window --begin 4 4 --inputbox "Password: " 0 0 \
			--and-widget    --keep-window --begin 6 6 --menu "Encryption:" 0 40 0 $_enc \
			2> $_serveradd_TEMP.selection

			[[ ! $? == 0 ]] && rm $_serveradd_TEMP* && return 1

			port=$(cat $_serveradd_TEMP.selection | awk -F'\t' '{print $1}')
			pass=$(cat $_serveradd_TEMP.selection | awk -F'\t' '{print $2}')
			method_id=$(cat $_serveradd_TEMP.selection | awk -F'\t' '{print $3}')
			method=$(cat $_serveradd_TEMP | sed -n "${method_id}p")

			debug "called add $port $pass $method"
			dialog --msgbox "$(add $port $pass $method)" 0 0

			cfm_restart

			rm $_serveradd_TEMP*
			return 0
		};;
		c) {
			local _serverctrl_TEMP=$(mktemp)

			dialog \
					--menu "Shadowmanager control:" 0 40 0 \
						s "(S)top shadowmanager" \
						t "s(T)art shadowmanager" \
						r "(R)estart shadowmanager" \
						u "Shadowmanager (S)tatus" \
						b "(B)ack" \
			2> $_serverctrl_TEMP
			[[ ! $? == 0 ]] && b > $_serverctrl_TEMP

			case $(cat $_serverctrl_TEMP) in
				s) {
					stop
					read -p "Press [ENTER] key to continue..."
				};;
				t) {
					start
					read -p "Press [ENTER] key to continue..."
				};;
				r) {
					restart
					read -p "Press [ENTER] key to continue..."
				};;
				u) {
					dialog --msgbox "$(status)" 0 0
				};;
				b) true ;;
			esac
			
			rm $_serverctrl_TEMP
			return 0
		};;
		r) {
			local _serveredit_TEMP="$(mktemp)"

			show | sed -e "1d" > $_serveredit_TEMP.list

			dialog \
					--menu "Select server: " 0 70 0 $(cat $_serveredit_TEMP.list) \
			2> $_serveredit_TEMP

			[[ ! $? == 0 ]] && rm $_serveredit_TEMP* && return 1
			
			remove $(cat $_serveredit_TEMP)
			rm $_serveredit_TEMP*
		};;
		o) {
			local _ovr_TEMP="$(mktemp)"
			
			let i=1

			local ovrarg=""

			for ovr in $(ls ./override-available/)
			do
				local onoff=off
				[[ -e ./override/$ovr ]] && local onoff=on
				local ovrarg="$ovrarg $i $ovr $onoff"
				let i++
			done
			
			dialog \
					--checklist "Select override(s) to use:" 0 0 0 $ovrarg \
			2> $_ovr_TEMP.selection

			[[ -z $(cat $_ovr_TEMP.selection) ]] && rm $_ovr_TEMP && return 0

			local ovr_target=$(ls ./override-available/|sed -n "$(cat $_ovr_TEMP.selection|sed -e 's/ /p; /g')p;")

			rm ./override/*

			enovr $ovr_target

			dialog --msgbox "Enabled override(s):\n $ovr_target" 0 0

			rm $_ovr_TEMP*
			return 0

		};;
		s) {
			dialog --msgbox "$(show)" 0 0
		};;
		p) {
			local _pluginui_temp=$(mktemp)
			local pluginarg=""
			IFS=$'\n'
			for plugin in $(cat $PLUGIN_UI_CFG)
			do
				thisname=$(echo $plugin | awk -F":" '{print $1}')
				thisfunc=$(echo $plugin | awk -F":" '{print $2}')
				pluginarg="$pluginarg $thisfunc $thisname "
			done
			
			[[ -z $pluginarg ]] && dialog --msgbox "No extra GUIs found." 5 30 

			IFS=" "

			dialog --menu "GUI Provided by overrides:" 0 75 0 $pluginarg
		};;
		e) {
			local _cmd_temp=$(mktemp)
			dialog --inputbox "Command:" 0 0 2> $_cmd_temp
			eval $(cat $_cmd_temp)
			read -p "Press [ENTER] key to continue..."
		};;
		q) {
			rm $TEMP
			exit 0
		};;
	esac
}
